FROM node:20-alpine

RUN apk add --no-cache libc6-compat tzdata
ENV TZ=Asia/Bangkok

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

COPY . .

RUN npx prisma generate

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
