export const ROUTES = {
  DASHBOARD: (locale: string) => `/${locale}/dashboard`,
  POS: (locale: string) => `/${locale}/pos`,
  SALES: (locale: string) => `/${locale}/sales`,
  PRODUCTS: {
    LIST: (locale: string) => `/${locale}/products/list`,
    ADD: (locale: string) => `/${locale}/products/add`,
    EDIT: (locale: string, id: string) => `/${locale}/products/edit/${id}`,
    DETAIL: (locale: string, id: string) => `/${locale}/products/${id}`,
  },
  INVENTORY: (locale: string) => `/${locale}/inventory`,
  SETTINGS: {
    INDEX: (locale: string) => `/${locale}/settings`,
    UNITS: (locale: string) => `/${locale}/settings/units`,
    CATEGORIES: (locale: string) => `/${locale}/settings/categories`,
    INGREDIENTS_AND_CONTAINERS: (locale: string) => `/${locale}/settings/ingredients-and-containers`,
    PRODUCT_TYPES: (locale: string) => `/${locale}/settings/product-types`,
    TOPPINGS: (locale: string) => `/${locale}/settings/toppings`,
    PROMOTIONS: (locale: string) => `/${locale}/settings/promotions`,
    USERS: (locale: string) => `/${locale}/settings/users`,
    ROLES: (locale: string) => `/${locale}/settings/roles`,
    WAREHOUSES: (locale: string) => `/${locale}/settings/warehouses`,
    THEME: (locale: string) => `/${locale}/settings/theme`,
  },
  LOGIN: (locale: string) => `/${locale}/login`,
} as const;
